### ISSUE TITLE
Special price products not showing

### ISSUE THREAD

**Issue by xiaolinwuu** [DominicWatts/Special#1]
`We can't find products matching the selection.
`
Special price products not showing even if I set the discount and the period range on them...
- [x] Remove from latest release

**Comment by DominicWatts** [comment]
What version magento? I will check this. But standard rules apply. Stock, status etc

**Comment by DominicWatts** [comment]
I checked with vanilla `2.2.6` install with sample data and product came through. 

https://github.com/DominicWatts/Special/issues/3

**Comment by DominicWatts** [comment]
Cant reproduce

**Comment by Songworks** [comment]
Having the same issue of getting the "None found" message.
I'm on Magento 2.3.2. Got three products with special prices which are visible on "normal categories" or search and with or without the `special_from_date` and/or `special_to_date` set.
I checked the `addAttributeToFilter` constraints, the products should match these.

Any idea how to debug this?
Logs don't show anything. Unfortunately I don't have the time to install and try around with sample data. :/

**Comment by Songworks** [comment]
Got it working by removing the `$collection->addAttributeToFilter('special_price', ['lt' => new \Zend_Db_Expr('at_price.value')]);` constraint in `Xigen\Special\Model\Layer::getProductCollection`.
Unfortunately I don't know enough about Magento to say why. Probably some configuration concerning the [flat catalog tables](https://magento.stackexchange.com/a/113669) (I don't have them enabled though) and what not?
But for now I'm happy with having it work at least partially. :)

**Comment by drinkingsouls** [comment]
> Got it working by removing the `$collection->addAttributeToFilter('special_price', ['lt' => new \Zend_Db_Expr('at_price.value')]);` constraint in `Xigen\Special\Model\Layer::getProductCollection`.
> Unfortunately I don't know enough about Magento to say why. Probably some configuration concerning the [flat catalog tables](https://magento.stackexchange.com/a/113669) (I don't have them enabled though) and what not?
> But for now I'm happy with having it work at least partially. :)

I had the same issue on Magento 2.3.4 and this worked for me. Thank you.

**Comment by DominicWatts** [comment]
Just curious on your problem products is your special price higher or equal to your standard price? Also did you try running price index?

**Comment by DominicWatts** [comment]
FYI I've removed from latest release https://github.com/DominicWatts/Special/releases/tag/1.1.8

**Comment by drinkingsouls** [comment]
> Just curious on your problem products is your special price higher or equal to your standard price? Also did you try running price index?

My special price is lower that my original price in all products. I did try reindex and deploy incase it was a caching issue. I could only get the module to work once I'd removed that line.
