### ISSUE TITLE
Call to a member function shouldDisplayProductCountOnLayer() on null 

### ISSUE THREAD

**Issue by drinkingsouls** [DominicWatts/Special#14]
HI Dominic,
This was working fine for me along with the new products module.
However, now I am getting the following error:

Error: Call to a member function shouldDisplayProductCountOnLayer() on null in /home/user/public_html/vendor/magento/module-layered-navigation/view/frontend/templates/layer/filter.phtml:21

Is there any solution to this?
Thank you.

**Comment by drinkingsouls** [comment]
I fixed this issue by editing app/design/frontend/themename/theme/Magento_LayeredNavigation/templates/layer/filter.phtml

Changed line 21 from

`<?php if ($viewModel->shouldDisplayProductCountOnLayer()): ?>`

to

`<?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>`

**Comment by DegrizNet** [comment]
In special_index_index.xml
change
`                <block class="Magento\LayeredNavigation\Block\Navigation\FilterRenderer" name="catalog.navigation.renderer" as="renderer" template="Magento_LayeredNavigation::layer/filter.phtml"/>`
to
`                <block class="Magento\LayeredNavigation\Block\Navigation\FilterRenderer" name="catalog.navigation.renderer" as="renderer" template="Magento_LayeredNavigation::layer/filter.phtml">
                    <arguments>
                        <argument name="product_layer_view_model" xsi:type="object">Magento\LayeredNavigation\ViewModel\Layer\Filter</argument>
                    </arguments>
                </block>`
