### ISSUE TITLE
 See exception log for details. Why?

### ISSUE THREAD

**Issue by VipinSimploics** [DominicWatts/Special#16]
When clicking on the "Special offer" link. it showing

![Screenshot from 2021-05-27 13-56-01](https://user-images.githubusercontent.com/78792991/119792706-899c8a00-bef3-11eb-9f23-d869ed488a4d.png)
![Screenshot from 2021-05-27 13-56-16](https://user-images.githubusercontent.com/78792991/119792727-8dc8a780-bef3-11eb-8315-e0a7642a3ae6.png)
![Screenshot from 2021-05-27 13-56-23](https://user-images.githubusercontent.com/78792991/119792736-902b0180-bef3-11eb-8455-3076e4039a54.png)

What is the reason for It? THe page will be appear if click on the exception link

**Comment by DominicWatts** [comment]
Was this issue https://magento.stackexchange.com/questions/344816/magento-2-4-3-issues-compatibility-issue-with-a-shop-by-brand-module

**Comment by DominicWatts** [comment]
Fixed in 1.1.10
