### ISSUE TITLE
Shopping Options showing error whenloading the page

### ISSUE THREAD

**Issue by VipinSimploics** [DominicWatts/Special#17]
![Screenshot from 2021-05-27 13-56-16](https://user-images.githubusercontent.com/78792991/120593115-a2a9bb80-c45c-11eb-84a5-2783157539e1.png)
![Screenshot from 2021-05-27 13-56-23](https://user-images.githubusercontent.com/78792991/120593121-a50c1580-c45c-11eb-9ecd-a9c5e79475c6.png)
![Screenshot from 2021-05-27 13-56-01](https://user-images.githubusercontent.com/78792991/120593129-a89f9c80-c45c-11eb-9d8f-4e2a5fb41390.png)
How can I fix it on Magento 2.4

**Comment by DominicWatts** [comment]
View source

Should see php error

**Comment by DominicWatts** [comment]
Error: Call to a member function getOptionsData() on null

**Comment by DominicWatts** [comment]
https://magento.stackexchange.com/questions/344816/magento-2-4-3-issues-compatibility-issue-with-a-shop-by-brand-module

Fixed in 1.1.10
