### ISSUE TITLE
Url from special offer page is wrong

### ISSUE THREAD

**Issue by Naberdz** [DominicWatts/Special#2]
our template uses function $_product->getProductUrl() which is default magento functionality, but from Special offer page it shows product url as  catalog/poruct/view/id/slug 

had to modify file: Block/Product/ListProduct.php
added following function:
```
    /**
     * Retrieve loaded category collection
     *
     * @return AbstractCollection
     */
    public function getLoadedProductCollection()
    {
        return $this->_getProductCollection()->addUrlRewrite();
    }
```

**Comment by DominicWatts** [comment]
Sounds logical. Can you create a pull request? Thanks

**Comment by Naberdz** [comment]
The following changes since commit f2b0688275d5a71eb62219a5b065ef8cad93ef67:

  Added URL rewrite support (2019-07-22 08:48:02 +0200)

are available in the Git repository at:

  ./ 

for you to fetch changes up to f2b0688275d5a71eb62219a5b065ef8cad93ef67:

  Added URL rewrite support (2019-07-22 08:48:02 +0200)
