### ISSUE TITLE
shopkeeper can not set title

### ISSUE THREAD

**Issue by YiffyToys** [DominicWatts/Special#21]
The widet always shows the title "Special Offers" (and doesn't come with translations for that title).
So the shopkeeper can not set a title for the different languages himself in the admin UI.

**Comment by DominicWatts** [comment]
Could you not create a translation file entry in your current theme?

**Comment by YiffyToys** [comment]
The "Install instructions" and "Usage instructions" don't cover how to do and deploy that.
All other modules have store admin properties for customer facing labels.
So doing that doesn't seem to be the norm to do it this way either.

From what I understand, how Magento works,
the language depends on the store view
while all store views share the theme for that store
and multiple stores can share any theme.

Even if a translation where to affect all stores,
specifically it's unclear how to specify what module's token are to be covered by a translation
as they don't seem to have any prefixes or other namespaces.

With no e.g. en-US and en-UK translation files in this module, 
it's also not obvious how to fork to add additional languages
as there is no short developer documentation.

**Comment by DominicWatts** [comment]
Mage 2 core stuff. But for example, if I were to add a translation for en_GB locale

    app\design\frontend\[vendor]\[theme]\i18n\en_GB.csv

"Special Offers", "Sale"

Happy coding
