### ISSUE TITLE
Magento 2.4.6 Compatibility

### ISSUE THREAD

**Issue by drinkingsouls** [DominicWatts/Special#22]
Depreciation of Zend Framework in Magento 2.4.6

Error: Class "Zend_Date" not found in /home/storm/sites/design-a-cake-com/public/app/code/Xigen/Special/Model/Layer.php:67

Added on line 8:
use DateTime;

Line 67 changes:
$date = new \Zend_Date();
$date = new DateTime();

Line 76 change:
'to' => $date->get('YYYY-MM-dd') . ' 23:59:59'
'to' => $date->format('Y-m-d')

Line 93 change:
'from' => $date->get('YYYY-MM-dd') . ' 00:00:00'
'from' => $date->format('Y-m-d')

I'm not certain about these changes, PHP is not my first language! In the original code the time is also specified, which I haven't.
There are other Zend references present such as Zend_Db_Expr that will probably need to be changed going forward.

**Comment by DominicWatts** [comment]
Updated in 1.2.0

Zend_Db_Expr is good in 2.4.6

Thanks

**Comment by drinkingsouls** [comment]
Just noticed:
Block/Widget/Special.php still contains Zend_Date line 83.

**Comment by DomPixie** [comment]
Yep - Updated in 1.2.1

Thanks
