### ISSUE TITLE
Layered Navigation not coming

### ISSUE THREAD

**Issue by Mrinza** [DominicWatts/Special#3]
I have installed the module on my 2 projects. But layered navigation are not coming in both projects. Can you please help on this

**Comment by DominicWatts** [comment]
What version magento? I will check this with sample data.

**Comment by Mrinza** [comment]
Magento Version 2.2.6

**Comment by DominicWatts** [comment]
I looked into this for you

I developed on `2.2.9` so most `2.2.x` versions should be compatible.

However I tried `2.2.6` with sample data.  So no modifications.  Didn't even change the sample data - so 1 product was set as special price.

![Screenshot-2019-7-21 Special Offers](https://user-images.githubusercontent.com/7295705/61596716-0aefab00-abff-11e9-9d6e-c170d3052a46.png)

![wK3uO6 jpg](https://user-images.githubusercontent.com/7295705/61596718-0d520500-abff-11e9-8db5-d2efb36379b5.png)

As you can see filters came through.  I can only suggest checking error logs.  Maybe something specific about your attribute and/or products.

Sorry I can't be of more help.

**Comment by Mrinza** [comment]
Thanks for your reply. Its working on luma theme. But not working on custom
theme. Listing is Fine. But layered navigation is not coming. Please check
this url

https://www.alsaifhome.com/special

Also on error log there is nothing. I have to do anything changes for
custom theme.

**Comment by tudn9x** [comment]
Hi @Mrinza I tested and It working fine on version 2.1.11

**Comment by DominicWatts** [comment]
Cant reproduce
